In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [12]:
def mae(y_true,y_predicted):
    total_error,mae=0,0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=(abs(yp-yt))
    mae=total_error/len(y_true)
    return mae

In [13]:
mae(y_true,y_predicted)

0.5

In [14]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [15]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [16]:
np.mean(np.abs(y_predicted - y_true)**2)

0.366

In [17]:
def mse(y_true,y_predicted):
    total_error,mse=0,0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=(abs(yp-yt)**2)
    mse=total_error/len(y_true)
    return mse

In [18]:
mse(y_true,y_predicted)

0.366

In [19]:
np.log([0])

C:\Users\DEXTER\AppData\Local\Temp\ipykernel_4872\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [20]:
np.log([0.000000000000001])

array([-34.53877639])

In [30]:
epsilon = 1e-15

In [31]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [32]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [33]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [34]:
np.log(y_predicted)

C:\Users\DEXTER\AppData\Local\Temp\ipykernel_4872\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [35]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [36]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [37]:
log_loss(y_true, y_predicted)

17.2696280766844