In [1]:
import numpy as np

In [3]:
companies=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [4]:
companies

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [7]:
companies_inr=companies*75

In [8]:
companies_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [9]:
ppu=np.array([[20,30,15]])

In [10]:
ppu

array([[20, 30, 15]])

In [11]:
sold=np.array([[50,60,25],[10,13,5],[40,70,52]])

In [13]:
r

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])